### ISSUE TITLE
moflask for python falcon

### ISSUE THREAD

**Issue by bochuxt** [moreonion/moflask#3]
I would like to use PingConnectionHandler for python falcon framework. How can i use it. Please help.

Thanks a lot.

**Comment by torotil** [comment]
The ProxyFix class is made to wrap a flask app object. But of course you can also use wrap a falcon API. Taking a quick glance at their API I’d guess something like this would work (untested):

```python
import falcon
from moflask.wsgi import ProxyFix
app = falcon.API()

class FlaskAppStub:
    wsgi_app = app

app = ProxyFix(FlaskAppStub)

```

**Comment by bochuxt** [comment]
i really appreciate your help and instant reply and i will have a try.
